# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import logging

class QTextEditorLogger(logging.Handler):
    def __init__(self, parent):
        super().__init__()
        self.widget = QtWidgets.QTextEdit(parent)
        # self.widget.setTextBackgroundColor()
        self.widget.setReadOnly(True)

    def emit(self, record):
        msg = self.format(record)
        self.widget.append(msg)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1228, 889)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.power_control = QtWidgets.QGroupBox(self.centralwidget)
        self.power_control.setGeometry(QtCore.QRect(700, 10, 231, 161))
        self.power_control.setObjectName("power_control")
        self.power_on = QtWidgets.QPushButton(self.power_control)
        self.power_on.setGeometry(QtCore.QRect(0, 20, 112, 34))
        self.power_on.setObjectName("power_on")
        self.label_2 = QtWidgets.QLabel(self.power_control)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 68, 19))
        self.label_2.setObjectName("label_2")
        self.voltage = QtWidgets.QLineEdit(self.power_control)
        self.voltage.setGeometry(QtCore.QRect(80, 60, 71, 31))
        self.voltage.setObjectName("voltage")
        self.label_3 = QtWidgets.QLabel(self.power_control)
        self.label_3.setGeometry(QtCore.QRect(160, 70, 68, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.power_control)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 68, 19))
        self.label_4.setObjectName("label_4")
        self.current = QtWidgets.QLineEdit(self.power_control)
        self.current.setGeometry(QtCore.QRect(80, 104, 71, 31))
        self.current.setObjectName("current")
        self.label_5 = QtWidgets.QLabel(self.power_control)
        self.label_5.setGeometry(QtCore.QRect(160, 110, 68, 19))
        self.label_5.setObjectName("label_5")
        self.power_off = QtWidgets.QPushButton(self.power_control)
        self.power_off.setGeometry(QtCore.QRect(120, 20, 101, 31))
        self.power_off.setObjectName("power_off")
        self.check_carriers = QtWidgets.QGroupBox(self.centralwidget)
        self.check_carriers.setGeometry(QtCore.QRect(20, 410, 371, 181))
        self.check_carriers.setCheckable(True)
        self.check_carriers.setObjectName("check_carriers")
        self.read_chip_temp = QtWidgets.QCheckBox(self.check_carriers)
        self.read_chip_temp.setGeometry(QtCore.QRect(50, 90, 151, 23))
        self.read_chip_temp.setObjectName("read_chip_temp")
        self.isolation = QtWidgets.QCheckBox(self.check_carriers)
        self.isolation.setGeometry(QtCore.QRect(50, 120, 141, 23))
        self.isolation.setObjectName("isolation")
        self.udhcp = QtWidgets.QCheckBox(self.check_carriers)
        self.udhcp.setGeometry(QtCore.QRect(50, 140, 101, 23))
        self.udhcp.setObjectName("udhcp")
        self.soap_msg = QtWidgets.QCheckBox(self.check_carriers)
        self.soap_msg.setGeometry(QtCore.QRect(50, 60, 131, 23))
        self.soap_msg.setObjectName("soap_msg")
        self.power = QtWidgets.QCheckBox(self.check_carriers)
        self.power.setGeometry(QtCore.QRect(50, 30, 101, 23))
        self.power.setChecked(True)
        self.power.setObjectName("power")
        self.power_read = QtWidgets.QLineEdit(self.check_carriers)
        self.power_read.setGeometry(QtCore.QRect(140, 30, 71, 21))
        self.power_read.setObjectName("power_read")
        self.label_7 = QtWidgets.QLabel(self.check_carriers)
        self.label_7.setGeometry(QtCore.QRect(220, 30, 61, 16))
        self.label_7.setObjectName("label_7")
        self.chamber_control = QtWidgets.QGroupBox(self.centralwidget)
        self.chamber_control.setGeometry(QtCore.QRect(950, 10, 221, 161))
        self.chamber_control.setObjectName("chamber_control")
        self.pushButton_3 = QtWidgets.QPushButton(self.chamber_control)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 20, 112, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.chamber_control)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 60, 112, 34))
        self.pushButton_4.setObjectName("pushButton_4")
        self.log_label = QtWidgets.QLabel(self.centralwidget)
        self.log_label.setGeometry(QtCore.QRect(440, 190, 68, 19))
        self.log_label.setObjectName("log_label")
        self.link_status = QtWidgets.QGroupBox(self.centralwidget)
        self.link_status.setGeometry(QtCore.QRect(30, 310, 371, 91))
        self.link_status.setCheckable(True)
        self.link_status.setObjectName("link_status")
        self.cpri_sync = QtWidgets.QCheckBox(self.link_status)
        self.cpri_sync.setGeometry(QtCore.QRect(50, 30, 121, 23))
        self.cpri_sync.setChecked(True)
        self.cpri_sync.setObjectName("cpri_sync")
        self.jesd = QtWidgets.QCheckBox(self.link_status)
        self.jesd.setGeometry(QtCore.QRect(50, 60, 101, 23))
        self.jesd.setChecked(True)
        self.jesd.setObjectName("jesd")
        self.cpri_sync_read = QtWidgets.QLineEdit(self.link_status)
        self.cpri_sync_read.setGeometry(QtCore.QRect(130, 30, 71, 21))
        self.cpri_sync_read.setObjectName("cpri_sync_read")
        self.jesd_read = QtWidgets.QLineEdit(self.link_status)
        self.jesd_read.setGeometry(QtCore.QRect(130, 60, 71, 21))
        self.jesd_read.setObjectName("jesd_read")
        self.label = QtWidgets.QLabel(self.link_status)
        self.label.setGeometry(QtCore.QRect(210, 30, 61, 16))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.link_status)
        self.label_6.setGeometry(QtCore.QRect(210, 60, 61, 16))
        self.label_6.setObjectName("label_6")
        self.cycle_time = QtWidgets.QLineEdit(self.centralwidget)
        self.cycle_time.setGeometry(QtCore.QRect(90, 670, 113, 25))
        self.cycle_time.setObjectName("cycle_time")
        self.loop_label = QtWidgets.QLabel(self.centralwidget)
        self.loop_label.setGeometry(QtCore.QRect(30, 670, 68, 21))
        self.loop_label.setObjectName("loop_label")
        self.start_test = QtWidgets.QPushButton(self.centralwidget)
        self.start_test.setGeometry(QtCore.QRect(90, 700, 112, 34))
        self.start_test.setObjectName("start_test")
        self.settings_btn = QtWidgets.QPushButton(self.centralwidget)
        self.settings_btn.setGeometry(QtCore.QRect(20, 120, 121, 34))
        self.settings_btn.setObjectName("settings_btn")
        self.dut_status = QtWidgets.QCheckBox(self.centralwidget)
        self.dut_status.setGeometry(QtCore.QRect(30, 270, 111, 17))
        self.dut_status.setChecked(True)
        self.dut_status.setObjectName("dut_status")
        self.psu_stress = QtWidgets.QCheckBox(self.centralwidget)
        self.psu_stress.setGeometry(QtCore.QRect(30, 240, 101, 17))
        self.psu_stress.setObjectName("psu_stress")
        self.generate_report = QtWidgets.QPushButton(self.centralwidget)
        self.generate_report.setGeometry(QtCore.QRect(240, 700, 101, 31))
        self.generate_report.setObjectName("generate_report")
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(90, 750, 111, 31))
        self.pause.setObjectName("pause")
        self.resume = QtWidgets.QPushButton(self.centralwidget)
        self.resume.setGeometry(QtCore.QRect(240, 750, 101, 31))
        self.resume.setObjectName("resume")
        self.log_window = QTextEditorLogger(self.centralwidget)
        self.log_window.widget.setGeometry(QtCore.QRect(440, 220, 631, 601))
        self.log_window.widget.setObjectName("log_window")
        # self.log_window = QtWidgets.QTextEdit(self.centralwidget)
        # self.log_window.setGeometry(QtCore.QRect(440, 220, 631, 601))
        # self.log_window.setObjectName("log_window")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1228, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.power_control.setTitle(_translate("MainWindow", "power control"))
        self.power_on.setText(_translate("MainWindow", "on"))
        self.label_2.setText(_translate("MainWindow", "Volatge"))
        self.voltage.setText(_translate("MainWindow", "48"))
        self.label_3.setText(_translate("MainWindow", "V"))
        self.label_4.setText(_translate("MainWindow", "Current"))
        self.label_5.setText(_translate("MainWindow", "A"))
        self.power_off.setText(_translate("MainWindow", "off"))
        self.check_carriers.setTitle(_translate("MainWindow", "Check Carriers"))
        self.read_chip_temp.setText(_translate("MainWindow", "Read Chip Temp"))
        self.isolation.setText(_translate("MainWindow", " 隔离度读取"))
        self.udhcp.setText(_translate("MainWindow", "UDHCP"))
        self.soap_msg.setText(_translate("MainWindow", "SOAP msg"))
        self.power.setText(_translate("MainWindow", "Power"))
        self.power_read.setText(_translate("MainWindow", "3"))
        self.label_7.setText(_translate("MainWindow", "read counts"))
        self.chamber_control.setTitle(_translate("MainWindow", "chamber control"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.log_label.setText(_translate("MainWindow", "log"))
        self.link_status.setTitle(_translate("MainWindow", "Link Status Test"))
        self.cpri_sync.setText(_translate("MainWindow", "CPRI Sync"))
        self.jesd.setText(_translate("MainWindow", "JESD"))
        self.cpri_sync_read.setText(_translate("MainWindow", "1"))
        self.jesd_read.setText(_translate("MainWindow", "3"))
        self.label.setText(_translate("MainWindow", "read counts"))
        self.label_6.setText(_translate("MainWindow", "read counts"))
        self.cycle_time.setText(_translate("MainWindow", "100"))
        self.loop_label.setText(_translate("MainWindow", "Cycle"))
        self.start_test.setText(_translate("MainWindow", "Start test"))
        self.settings_btn.setText(_translate("MainWindow", "Settings"))
        self.dut_status.setText(_translate("MainWindow", "Dut status check"))
        self.psu_stress.setText(_translate("MainWindow", "PSU stress test"))
        self.generate_report.setText(_translate("MainWindow", "Generate Report"))
        self.pause.setText(_translate("MainWindow", "Pause"))
        self.resume.setText(_translate("MainWindow", "Resume"))

