# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_subwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(621, 551)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 100, 91, 19))
        self.label.setObjectName("label")
        self.frequency = QtWidgets.QLineEdit(Dialog)
        self.frequency.setGeometry(QtCore.QRect(170, 100, 113, 25))
        self.frequency.setObjectName("frequency")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 150, 68, 19))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 68, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 180, 68, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 220, 68, 19))
        self.label_5.setObjectName("label_5")
        self.band_width = QtWidgets.QLineEdit(Dialog)
        self.band_width.setGeometry(QtCore.QRect(170, 140, 113, 25))
        self.band_width.setObjectName("band_width")
        self.power = QtWidgets.QLineEdit(Dialog)
        self.power.setGeometry(QtCore.QRect(170, 180, 113, 25))
        self.power.setObjectName("power")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(300, 100, 68, 19))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(300, 140, 68, 19))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(300, 180, 68, 19))
        self.label_12.setObjectName("label_12")
        self.tm = QtWidgets.QComboBox(Dialog)
        self.tm.setGeometry(QtCore.QRect(170, 220, 121, 25))
        self.tm.setObjectName("tm")
        self.tm.addItem("")
        self.save_btn = QtWidgets.QPushButton(Dialog)
        self.save_btn.setGeometry(QtCore.QRect(380, 380, 112, 34))
        self.save_btn.setObjectName("save_btn")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(50, 70, 51, 16))
        self.label_13.setObjectName("label_13")
        self.made_num = QtWidgets.QComboBox(Dialog)
        self.made_num.setGeometry(QtCore.QRect(170, 70, 111, 22))
        self.made_num.setObjectName("made_num")
        self.made_num.addItem("")
        self.made_num.addItem("")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(50, 40, 81, 16))
        self.label_14.setObjectName("label_14")
        self.rru_mode = QtWidgets.QComboBox(Dialog)
        self.rru_mode.setGeometry(QtCore.QRect(170, 40, 69, 22))
        self.rru_mode.setObjectName("rru_mode")
        self.rru_mode.addItem("")
        self.rru_mode.addItem("")
        self.rru_mode.addItem("")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 260, 61, 21))
        self.label_6.setObjectName("label_6")
        self.test_type = QtWidgets.QComboBox(Dialog)
        self.test_type.setGeometry(QtCore.QRect(170, 260, 81, 22))
        self.test_type.setObjectName("test_type")
        self.test_type.addItem("")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 310, 101, 16))
        self.label_7.setObjectName("label_7")
        self.pusch_rb_offset = QtWidgets.QLineEdit(Dialog)
        self.pusch_rb_offset.setGeometry(QtCore.QRect(172, 310, 81, 20))
        self.pusch_rb_offset.setObjectName("pusch_rb_offset")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(50, 350, 111, 16))
        self.label_8.setObjectName("label_8")
        self.pdsch_power_backoff = QtWidgets.QLineEdit(Dialog)
        self.pdsch_power_backoff.setGeometry(QtCore.QRect(170, 350, 81, 20))
        self.pdsch_power_backoff.setObjectName("pdsch_power_backoff")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(50, 390, 61, 16))
        self.label_9.setObjectName("label_9")
        self.ul_mode = QtWidgets.QComboBox(Dialog)
        self.ul_mode.setGeometry(QtCore.QRect(170, 390, 69, 22))
        self.ul_mode.setObjectName("ul_mode")
        self.ul_mode.addItem("")
        self.ul_mode.addItem("")
        self.reset = QtWidgets.QPushButton(Dialog)
        self.reset.setGeometry(QtCore.QRect(380, 420, 111, 31))
        self.reset.setObjectName("reset")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(50, 440, 61, 16))
        self.label_15.setObjectName("label_15")
        self.auto_gen = QtWidgets.QComboBox(Dialog)
        self.auto_gen.setGeometry(QtCore.QRect(170, 440, 69, 22))
        self.auto_gen.setObjectName("auto_gen")
        self.auto_gen.addItem("")
        self.auto_gen.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "频率"))
        self.frequency.setText(_translate("Dialog", "3500"))
        self.label_3.setText(_translate("Dialog", "带宽"))
        self.label_4.setText(_translate("Dialog", "功率"))
        self.label_5.setText(_translate("Dialog", "TM"))
        self.band_width.setText(_translate("Dialog", "100"))
        self.power.setText(_translate("Dialog", "37.95"))
        self.label_10.setText(_translate("Dialog", "MHz"))
        self.label_11.setText(_translate("Dialog", "MHz"))
        self.label_12.setText(_translate("Dialog", "dBm"))
        self.tm.setItemText(0, _translate("Dialog", "TM3_1A"))
        self.save_btn.setText(_translate("Dialog", "Save"))
        self.label_13.setText(_translate("Dialog", "Made num"))
        self.made_num.setItemText(0, _translate("Dialog", "4"))
        self.made_num.setItemText(1, _translate("Dialog", "8"))
        self.label_14.setText(_translate("Dialog", "RRU_MODE"))
        self.rru_mode.setItemText(0, _translate("Dialog", "AEQZ"))
        self.rru_mode.setItemText(1, _translate("Dialog", "AEQV"))
        self.rru_mode.setItemText(2, _translate("Dialog", "AEQB"))
        self.label_6.setText(_translate("Dialog", "Test type"))
        self.test_type.setItemText(0, _translate("Dialog", "Test Mode"))
        self.label_7.setText(_translate("Dialog", "pusch_rb_offset"))
        self.pusch_rb_offset.setText(_translate("Dialog", "0"))
        self.label_8.setText(_translate("Dialog", "pdsch_power_backoff"))
        self.pdsch_power_backoff.setText(_translate("Dialog", "0"))
        self.label_9.setText(_translate("Dialog", "ul_mode"))
        self.ul_mode.setItemText(0, _translate("Dialog", "A1-5"))
        self.ul_mode.setItemText(1, _translate("Dialog", "A2-5"))
        self.reset.setText(_translate("Dialog", "Reset"))
        self.label_15.setText(_translate("Dialog", "auto_gen"))
        self.auto_gen.setItemText(0, _translate("Dialog", "False"))
        self.auto_gen.setItemText(1, _translate("Dialog", "True"))

